/**
 * Copyright 2023–2025 Waii, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


import WAII from '../src/waii-sdk';
import process = require("node:process");

const connection = "http://localhost:9859/api/";

async function main() {
    console.log('-----Initializing WAII-----');
    WAII.initialize(connection, '');

    
    let dbConnection =
        await WAII.Database.modifyConnections(
            {
                updated: [{
                    key: '', // will be generated by the system
                    account_name: '<your account name>',
                    database: '<your database>',
                    warehouse: '<your warehouse>',
                    role: '<your role>',
                    username: '<your username>',
                    password: '<your password>',
                    db_type: 'snowflake',
                }]
            }
        );

    //activating the database connection
    if (dbConnection.connectors) {
        WAII.Database.activateConnection(dbConnection.connectors[2].key);
    }

    //generating a query
    let genQuery = await WAII.Query.generate({
        ask: 'show me all the tables in this database'
    });

    console.log('-----Generated Query-----');
    console.log(genQuery);

    //running the query
    if(genQuery.query){
        let result = await WAII.Query.run({
            query: genQuery.query
        });
        console.log('-----Result of Query-----');
        console.log(result);
    }
    
    //getting the semantic context
    let semanticContext = await WAII.SemanticContext.getSemanticContext();
    console.log('-----Semantic Context-----');
    console.log(semanticContext);

    //getting query history
    let queryHistory = await WAII.History.list();
    console.log('-----Query History-----');
    console.log(queryHistory);
    
    process.exit(0);
}

main();
