import WAII from '../src/waii-sdk';

const connection = "http://localhost:9859/api/";

async function main() {
    WAII.initialize(connection, '');

    
    let dbConnection =
        await WAII.Database.modifyConnections(
            {
                updated: [{
                    key: '', // will be generated by the system
                    account_name: '<your account name>',
                    database: '<your database>',
                    warehouse: '<your warehouse>',
                    role: '<your role>',
                    username: '<your username>',
                    password: '<your password>',
                    db_type: 'snowflake',
                }]
            }
        );

    //activating the database connection
    if (dbConnection.connectors) {
        WAII.Database.activateConnection(dbConnection.connectors[2].key);
    }

    //generating a query
    let genQuery = await WAII.Query.generate({
        ask: 'show me all the tables in this database'
    });

    console.log('-----Generated Query-----');
    console.log(genQuery);

    //running the query
    if(genQuery.query){
        let result = await WAII.Query.run({
            query: genQuery.query
        });
        console.log('-----Result of Query-----');
        console.log(result);
    }
    
    //getting the semantic context
    let semanticContext = await WAII.SemanticContext.getSemanticContext();
    console.log('-----Semantic Context-----');
    console.log(semanticContext);

    //getting query history
    let queryHistory = await WAII.History.list();
    console.log('-----Query History-----');
    console.log(queryHistory);
    
    
}

main();